---
argument_specs:
  main:
    short_description: Install docker
    description:
      - Install docker on a host
    options:
      setup_docker_ipv4_cidr:
        type: 'str'
        default: '172.30.0.0/16'
        required: false
        description:
          - 'IPv4 cidr to use for new networks'
      setup_docker_ipv4_subnet_size:
        type: 'int'
        default: 26
        required: false
        description:
          - 'Size of new IPv4 subnets'
      setup_docker_ipv6_enabled:
        type: 'bool'
        default: true
        required: false
        description:
          - 'Enable IPv6 for docker daemon'
      setup_docker_ipv6_cidr:
        type: 'str'
        default: '2001:780:250:9::/64'
        required: false
        description:
          - 'IPv6 cidr to use for new networks'
      setup_docker_ipv6_subnet_size:
        type: 'int'
        default: 80
        required: false
        description:
          - 'Size of new IPv6 subnets'
...
