---
setup_podman_ipv4_cidr: "172.30.0.0/16"
setup_podman_ipv4_subnet_size: 26
# setup_podman_ipv6_enabled: true
# setup_podman_ipv6_cidr: "2001:780:250:9::/64"
# setup_podman_ipv6_subnet_size: 80
...
