---
- name: 'Run OS Specific Patch'
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml'
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yaml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yaml'
    - '{{ ansible_os_family }}.yml'
...
