---
galaxy_info:
  author: Lars Lehmann
  description: Setup motd
  # company: p5x

  role_name: motd
  namespace: p5x

  license: BSD-3-Clause
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags: []

dependencies: []
...
