---
- name: 'Debian: Upgrade all packages'
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true

- name: 'Debian: Check if a reboot is needed'
  when: 'update_os_auto_reboot'
  block:
    - name: 'Debian: Check if a reboot-required file exists'
      register: 'update_os_reboot_required_file'
      ansible.builtin.stat:
        path: '/var/run/reboot-required'

    - name: 'Debian: Reboot the box if kernel updated'
      ansible.builtin.reboot:
        msg: 'Reboot initiated by Ansible for kernel updates'
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: 'uptime'
      when: 'update_os_reboot_required_file.stat.exists'
...
