---
# - name: 'Add apt repo'
#   ansible.builtin.deb822_repository:
#     name: 'docker'
#     types: 'deb'
#     uris: 'https://download.docker.com/linux/debian'
#     suites: 'bookworm'
#     components:
#       - 'stable'
#     signed_by: 'https://download.docker.com/linux/debian/gpg'

- name: 'Install packages'
  ansible.builtin.apt:
    pkg:
      - 'podman'
      - 'podman-compose'
    update_cache: true
    state: 'present'

# - name: 'Create containers.conf'
#   ansible.builtin.template:
#     src: 'containers.conf.j2'
#     dest: '/etc/containers/containers.conf'
#     owner: 'root'
#     group: 'root'
#     mode: '0644'
#   notify: 'Restart podman service'

- name: 'Enable podman service'
  ansible.builtin.systemd_service:
    name: 'podman'
    enabled: true
    daemon_reload: true
  notify: 'Restart podman service'
...
